version: "3"
services:
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - "arkora-mysql:/var/lib/mysql"
    networks:
      - arkora

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - arkora

networks:
  arkora:
    driver: bridge

volumes:
  arkora-mysql:
    driver: local
