name: CI

on: [push]

jobs:
  staging_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/client
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: yarn

      - name: Lint Code
        run: yarn lint

      - name: Deploy to Staging
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_CLIENT_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "apps/client"
          procfile: "bin/start-nginx-solo yarn serve"

  staging_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/server
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Copy ENV
        run: cp .env.example .env

      - name: Install Dependencies
        run: yarn

      # Prevent default MySql server from running
      - name: Shutdown Ubuntu MySql
        run: sudo service mysql stop

      - name: Setup MySql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: "8.0"
          mysql database: ${{secrets.MYSQL_DATABASE}}
          mysql user: ${{secrets.MYSQL_USER}}
          mysql password: ${{secrets.MYSQL_PASSWORD}}

      - name: Wait MySql
        run: |
          while ! mysqladmin ping --host 127.0.0.1 --password=$DB_PASSWORD --silent; do
            sleep 1
          done

      - name: Lint Code
        run: yarn lint

      - name: Test Code
        run: |
          node ace migration:run
          yarn test

      - name: Deploy to Staging
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "apps/server"
          procfile: "web: node build/server.js release: node build/ace migration:run --force"
